# Generated by Django 5.1.6 on 2025-02-20 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'student'), ('department', 'Department')], default='Student', max_length=100)),
                ('year_of_study', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('head_of_department', models.ForeignKey(blank=True, limit_choices_to={'Role': 'head_of_department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to='AITS.customuser')),
            ],
        ),
    ]
